### ISSUE TITLE
Redoc demo readFile undefined

### ISSUE THREAD

**Issue by ocole007** [Redocly/redoc#2009]
**Describe the bug**
When we use the "Try It" feature at https://redocly.github.io/redoc/ e.g. https://redocly.github.io/redoc/?url=https://docs.graphhopper.com/openapi.json, an exception is raised.

**Expected behavior**
The URL passed to redoc should render the based on the swagger JSON description.

**Minimal reproducible OpenAPI snippet(if possible)**

**Screenshots**
![image](https://user-images.githubusercontent.com/90059135/168378939-12237528-bcad-40f5-b3a7-f306698adefd.png)

Cannot read properties of undefined (reading 'readFile')
Stack trace
Error: Cannot read properties of undefined (reading 'readFile')
    at t.BaseResolver.<anonymous> (https://redocly.github.io/redoc/redoc-demo.bundle.js:2:27238)
    at Generator.next (<anonymous>)
    at https://redocly.github.io/redoc/redoc-demo.bundle.js:2:25385
    at new Promise (<anonymous>)
    at r (https://redocly.github.io/redoc/redoc-demo.bundle.js:2:25130)
    at t.BaseResolver.loadExternalRef (https://redocly.github.io/redoc/redoc-demo.bundle.js:2:27020)
    at t.BaseResolver.<anonymous> (https://redocly.github.io/redoc/redoc-demo.bundle.js:2:27751)
    at Generator.next (<anonymous>)
    at https://redocly.github.io/redoc/redoc-demo.bundle.js:2:25385
    at new Promise (<anonymous>)

ReDoc Version: 2.0.0-rc.68
Commit: 494122f9
**Additional context**

**Comment by AlexVarchuk** [comment]
Hi @ocole007, we released the next version `2.0.0-rc.69`. It works for me.

<img width="985" alt="Screenshot 2022-05-15 at 11 33 58" src="https://user-images.githubusercontent.com/14113673/168464172-c473cb49-42ca-4049-a663-cd3074dd3f7d.png">

**Comment by jaaufauvre** [comment]
Hi @AlexVarchuk, 

Edge 101.0.1210.47, Chrome 101.0.4951.64, Brave 101.0.4951.41

Windows 10, Windows 11

:heavy_check_mark: https://redocly.github.io/redoc/?url=https://api.apis.guru/v2/specs/googleapis.com/calendar/v3/openapi.yaml&nocors

:x: https://redocly.github.io/redoc/?url=https://api.apis.guru/v2/specs/googleapis.com/calendar/v3/openapi.yaml 

```
Something went wrong...
Cannot read properties of undefined (reading 'readFile')
Stack trace
Error: Cannot read properties of undefined (reading 'readFile')
    at t.BaseResolver.<anonymous> (https://redocly.github.io/redoc/redoc-demo.bundle.js:2:27238)
    at Generator.next (<anonymous>)
    at https://redocly.github.io/redoc/redoc-demo.bundle.js:2:25385
    at new Promise (<anonymous>)
    at r (https://redocly.github.io/redoc/redoc-demo.bundle.js:2:25130)
    at t.BaseResolver.loadExternalRef (https://redocly.github.io/redoc/redoc-demo.bundle.js:2:27020)
    at t.BaseResolver.<anonymous> (https://redocly.github.io/redoc/redoc-demo.bundle.js:2:27751)
    at Generator.next (<anonymous>)
    at https://redocly.github.io/redoc/redoc-demo.bundle.js:2:25385
    at new Promise (<anonymous>)

ReDoc Version: 2.0.0-rc.68
Commit: 494122f9
```

![image](https://user-images.githubusercontent.com/3964455/168640878-c108a8d6-07d5-4102-b893-975828f4a964.png)

**Comment by AlexVarchuk** [comment]
@jaaufauvre we redeployed the demo page.
Hopes it helps. Please check.

**Comment by jaaufauvre** [comment]
Hi @AlexVarchuk, nop it didn't help. It works with Firefox though.

**Comment by ocole007** [comment]
Hi @AlexVarchuk ,  upon further inspection, this could be a CORS issue as I tested without CORS checked and it worked in some instances.

**Comment by AlexVarchuk** [comment]
Hi @ocole007. Seems it can be true. We have a special checkbox for it. One of the cases should be working.

**Comment by jaaufauvre** [comment]
Yes, this is what I mentioned earlier ☝
✔️ https://redocly.github.io/redoc/?url=https://api.apis.guru/v2/specs/googleapis.com/calendar/v3/openapi.yaml&nocors
❌ https://redocly.github.io/redoc/?url=https://api.apis.guru/v2/specs/googleapis.com/calendar/v3/openapi.yaml

**Comment by AlexVarchuk** [comment]
I close this issue. Because it is expected behavior. The demo page should work in one of the CORS cases (enabled/disabled).

**Comment by ayame113** [comment]
> The demo page should work in one of the CORS cases (enabled/disabled).

It looks like this problem still exists.

- https://redocly.github.io/redoc/?url=https://apiland.deno.dev/~/spec&nocors -> It fails with a CORS error.
- https://redocly.github.io/redoc/?url=https://apiland.deno.dev/~/spec -> Chrome on windows fails with `Cannot read properties of undefined (reading 'readFile')` error. works fine in firefox.

----

I've debugged this and it seems that different browsers have different ways of handling the URL constructor.
The code below returns different results.

```js
new URL("\\\\cors.redoc.ly/https://apiland.deno.dev/~/spec", "https://redocly.github.io/redoc/?url=https://apiland.deno.dev/~/spec")
```

![image](https://user-images.githubusercontent.com/40050810/205214142-36d300cc-ee98-450a-86f3-7da97e98ae22.png)
![image](https://user-images.githubusercontent.com/40050810/205214316-d6120994-08e0-43ac-905d-eda2edf603b6.png)

I think maybe correcting the url in this line from `\\\\cors.redoc.ly/` to `https://cors.redoc.ly/` will fix the problem.

https://github.com/Redocly/redoc/blob/3d410b6002c656efa780254c9c45c6249f90bce1/demo/index.tsx#L89
